### ISSUE TITLE
Postman.collections.forEach(function(collection)

### ISSUE THREAD

**Issue by wgosse** [f1nnix/docman#2]
Getting an error when running against a dump with a single collection with sub folders:
C:\Users\wgosse>docman C:\Dev\MoasisApi_PostmanTests\Moasis_API.json.postman_col
lection c:\temp\api_docs
Postman dump file path: C:\Dev\MoasisApi_PostmanTests\Moasis_API.json.postman_co
llection
Output directory: c:\temp\api_docs
C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\lib\generators\index.js:
11
    Postman.collections.forEach(function(collection) {
                       ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports [as index](C:UserswgosseAppDataRoamingnpmnod
e_modulesdocmanlibgeneratorsindex.js:11:24)
    at module.exports (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\l
ib\docman.js:15:16)
    at Object.<anonymous> (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docm
an\bin\docman.js:38:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by wgosse** [comment]
I closed this issue because I was running against the wrong file.

**Comment by parthibann** [comment]
I have specified correct input file but still im facing the issue.

**Comment by f1nnix** [comment]
@parthibann Please, consider creating a new issue with a test file. I'm going to release a re-written from scratch app soon, would be happy to fix your bug.
